apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curl
  name: test-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-client
    spec:
      containers:
      - image: curlimages/curl
        name: curl
        command: ["sleep", "365d"]
