apiVersion: v1
kind: Service
metadata:
  labels:
    app: guestbook-web
  name: guestbook-web
  namespace: guestbook
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: guestbook-web
    nodePort: 30800
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: guestbook-ui
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}