apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: guestbook
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: guestbook-ui
    - apiVersion: v1
      kind: Service
      name: guestbook-ui
    - apiVersion: v1
      kind: Service
      name: guestbook-web
  placement:
    clusterAffinity:
      clusterNames:
        - proxmox-member-1
        - proxmox-member-2
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - proxmox-member-1
            weight: 1
          - targetCluster:
              clusterNames:
                - proxmox-member-2
            weight: 1

